def setup():
    result = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
    result += "<quiz>\n" \
              "<!-- question: 0  -->\n" \
              "\t<question type=\"category\">\n" \
              "\t\t<category>\n" \
              "\t\t\t<text>Generated by QGen</text>\n" \
              "\t\t</category>\n" \
              "\t</question>\n"
    output_file = open("qgen_result.xml", "w")
    output_file.write(result)
    output_file.close()


def build_question_for_xml(title=None, text=None, type=None):
    result = "\n\t<question type=\"" + type + "\">"
    result += "<name>\n" + "\t\t<text>" + title + "</text>\n" + "\t\t</name>"
    result += "<questiontext format=\"html\">\n" + "\t\t<text>" + text + "</text>\n" + "\t\t</questiontext>"
    result += "<generalfeedback format=\"html\">\n" \
              "\t\t<text></text>\n" \
              "\t\t</generalfeedback>\n" \
              "\t\t<defaultgrade>1.0000000</defaultgrade>\n" \
              "\t\t<penalty>0.1000000</penalty>\n" \
              "\t\t<hidden>0</hidden>\n" \
              "\t\t<single>true</single>\n" \
              "\t\t<shuffleanswers>true</shuffleanswers>\n" \
              "\t\t<answernumbering>abc</answernumbering>\n" \
              "\t\t<correctfeedback format=\"html\">\n" \
              "\t\t\t<text></text>\n" \
              "\t\t</correctfeedback>\n" \
              "\t\t<partiallycorrectfeedback format=\"html\">\n" \
              "\t\t\t<text></text>\n" \
              "\t\t</partiallycorrectfeedback>\n" \
              "\t\t<incorrectfeedback format=\"html\">\n" \
              "\t\t\t<text></text>\n" \
              "\t\t</incorrectfeedback>\n"
    output_file = open("qgen_result.xml", "a+")
    output_file.write(result)
    output_file.close()


def build_answer_for_xml(text, correct_feedback=None):
    if correct_feedback == None:
        correct_feedback = ''
    result = "\n\t\t<answer fraction=\"0\" format=\"moodle_auto_format\">\n" + "\t\t\t<text>" + text + \
             "</text>\n" \
             "\t\t\t<feedback format=\"html\">\n" \
             "\t\t\t\t<text>" + correct_feedback + "</text>\n" \
                                                   "\t\t\t</feedback>\n" \
                                                   "\t\t</answer>\n"
    output_file = open("qgen_result.xml", "a+")
    output_file.write(result)
    output_file.close()


def build_distractor_for_xml(text, incorrect_feedback=None):
    if incorrect_feedback == None:
        incorrect_feedback = ''
    result = "\n\t\t<answer fraction=\"0\" format=\"moodle_auto_format\">\n" + "\t\t\t<text>" + text + \
             "</text>\n" \
             "\t\t\t<feedback format=\"html\">\n" \
             "\t\t\t\t<text>" + incorrect_feedback + "</text>\n" \
                                                     "\t\t\t</feedback>\n" \
                                                     "\t\t</answer>\n"
    output_file = open("qgen_result.xml", "a+")
    output_file.write(result)
    output_file.close()


def build_question_end_tag():
    result = "\t</question>\n\n"
    output_file = open("qgen_result.xml", "a+")
    output_file.write(result)
    output_file.close()


def build_quiz_end_tag():
    result = "</quiz>"
    output_file = open("qgen_result.xml", "a+")
    output_file.write(result)
    output_file.close()
